### ISSUE TITLE
openssl_lib_name doesn't work w/ a string literal, requires an explicit type coersion

### ISSUE THREAD

**Issue by devhawk** [karlseguin/pg.zig#65]
Attempting to specify `openssl_lib_name` as [described in the readme](https://github.com/karlseguin/pg.zig?tab=readme-ov-file#tls-experimental) fails to compile on 0.14.0

```zig
    const pg = b.dependency("pg", .{
        .target = target,
        .optimize = optimize,
        .openssl_lib_name = "ssl",
    });
```

result:

```shell
$ zig build
~/zig/0.14.0/files/lib/std/Build.zig:498:25: error: option 'openssl_lib_name' has unsupported type: *const [3:0]u8
                else => @compileError("option '" ++ field.name ++ "' has unsupported type: " ++ @typeName(T)),
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    dependencyInner__anon_68438: /home/harry/zig/0.14.0/files/lib/std/Build.zig:2389:56
    dependency__anon_64898: /home/harry/zig/0.14.0/files/lib/std/Build.zig:2230:35
    8 reference(s) hidden; use '-freference-trace=10' to see all references
```

Can be resolved by casting the string literal to `[]const u8`

```zig
    const pg = b.dependency("pg", .{
        .target = target,
        .optimize = optimize,
        .openssl_lib_name = @as([]const u8, "ssl"),
    });
```

**Comment by karlseguin** [comment]
Thanks. As far as I can tell, what you did is the right approach. Googling around suggest that Zig's std.Build.option is pretty limited in the types that it supports, and won't accept a string literal (*[n:0]u8) into a string slice.
